name: Simple Workflow

on:
  push:
    branches: [ master ]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print Greeting
        run: echo "Hello, GitHub Actions!"
